{{
  config(
    materialized='table'
  )
}}

-- Summary: FIRST STEP

-- KEY COLUMNS ADDED: ELIGIBLE_START_DATE, EDD_ONLINE_SUB_LAST_30, ELIGIBLE_END_DATE, ORDER_DATE, AS ACCOUNT_NUMBER, ACCOUNT_TYPE, ACTIVATION_DATE, DISCONNECTION_DATE, DISCONNECT_REASON,EXCESS_DISCONNECT_REASON, RECONNECT_DATE, MASTER_AGENT, EXCESS_MASTER, RETAILER, AGENT_NAME, EXCESS_RETAILER, ORDER_BY, PLAN, DEVICE_ID_IMEI, MAKE_MODEL, PRODUCT_TYPE, MDN, MDN_CLEAN, SOURCE, CHANNEL, SUBSCRIBER_STATUS, ENROLLMENT_TYPE, COMPLIANCE_INVALID_ENROLLMENT, FCC_COMPLIANT, CUSTOMER_NOTE, USAGE_NOTE

WITH omdb AS (
    SELECT
    IMDB_ID
    , TITLE
    , RATED
    , GENRE
    , DIRECTOR
    , WRITER
    , ACTORS
    , PLOT
    , LANGUAGE
    , COUNTRY
    , AWARDS
    , POSTER
    , IMDBID
    , TYPE
    , DVD
    , PRODUCTION
    , WEBSITE
    , RELEASE_YEAR
    , RELEASED_DATE
    , RUNTIME
    , RATINGS
    , METASCORE
    , IMDB_RATING
    , IMDB_VOTES
    , BOX_OFFICE
    , TMDB_ID
    FROM
       movie_challenge.public.omdb_movies o
),

tmdb AS (
    SELECT
    TMDB_ID
    , TITLE
    , ORIGINAL_TITLE
    , OVERVIEW
    , TAGLINE
    , KEYWORDS
    , ORIGINAL_LANGUAGE
    , STATUS
    , VIDEO
    , RELEASE_DATE
    , RUNTIME
    , BUDGET
    , REVENUE
    , VOTE_AVERAGE
    , VOTE_COUNT
    , HOMEPAGE
    , POSTER_PATH
    , BACKDROP_PATH
    , BELONGS_TO_COLLECTION
    , IMDB_ID
    , GENRE_NAMES
    , SPOKEN_LANGUAGES
    , PRODUCTION_COMPANY_NAMES
    , PRODUCTION_COUNTRY_NAMES
    FROM
       movie_challenge.public.tmdb_movies o
)

-- SELECT IMDB_ID, TITLE, RATED, GENRE, DIRECTOR, LANGUAGE, COUNTRY, AWARDS, IMDBID, TYPE, RELEASE_YEAR, RELEASED_DATE, RUNTIME, METASCORE
select i.*
    , t.ORIGINAL_TITLE as tmdb_original_title
    , t.OVERVIEW as tmdb_OVERVIEW
    , t.KEYWORDS as tmdb_KEYWORDS
    , t.STATUS as tmdb_STATUS
    , t.VOTE_AVERAGE as tmdb_VOTE_AVERAGE
    , t.VOTE_COUNT as tmdb_VOTE_COUNT
from omdb i
left join tmdb t on t.IMDB_ID = i.IMDB_ID