name: "paradime_movie_challenge"
version: "1.0.0"
config-version: 2

profile: "paradime-movie-challenge"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

query-comment:
  comment: '{{ get_query_comment(node) }}'
  append: true

models:
  paradime_movie_challenge: 
    sources:
      +schema: staging
      +materialized: view
    example_transformations:
      intermediate:
        +schema: intermediate
        +materialized: view  
    intermediate:
      +schema: intermediate
      +materialized: table
    warehouse:
      +schema: warehouse
      +materialized: table