SELECT
  Y.DECADE AS RELEASE_DECADE,
  AVG(G.NUMBER_OF_GENRES_THIS_MOVIE) AS AVG_NUMBER_OF_GENRES_PER_MOVIE
FROM {{ ref('int_movies_genres') }} AS G
LEFT JOIN {{ ref('movies') }} AS M ON G.IMDB_ID = M.IMDB_ID
LEFT JOIN {{ ref('all_years') }} AS Y ON M.RELEASE_YEAR = Y.DATE_YEAR
WHERE
  1 = 1
  AND Y.DECADE IS NOT NULL
GROUP BY 1
