WITH CTE AS (

  SELECT
    COMBINED_RATING,
    BUDGET_ADJUSTED
  FROM {{ ref('movies') }}
  WHERE
    1 = 1
    AND IMDB_VOTES > 999
    AND COMBINED_RATING IS NOT NULL
  ORDER BY IMDB_VOTES DESC
  LIMIT 500
)

SELECT REGR_R2(BUDGET_ADJUSTED, COMBINED_RATING) FROM CTE
