select
RELEASE_YEAR,
ROUND(avg(ADJ_BOX_OFFICE),1) AS AVG_BOX_OFFICE,
COUNT(*) AS TOTAL_FILMS,
ROUND(AVG(RUNTIME),1) AS AVG_RUNTIME
FROM
{{ source('PARADIME_MOVIE_CHALLENGE_FINAL', 'OMDB_INFLATION_ADJUSTED') }} a
WHERE ADJ_BOX_OFFICE>0
GROUP BY RELEASE_YEAR
