select production,
release_year,
sum(ADJ_BOX_OFFICE) AS TOTAL_BOX_OFFICE
FROM
{{ source('PARADIME_MOVIE_CHALLENGE_FINAL', 'OMDB_INFLATION_ADJUSTED') }}
WHERE RELEASE_YEAR>1990
GROUP BY PRODUCTION, RELEASE_YEAR
HAVING TOTAL_BOX_OFFICE >0
ORDER BY PRODUCTION,RELEASE_YEAR