version: 2
models:
  - name: stg_tmdb_movies
    description: >-
      The Movie Database (TMDb) is a community built movie and TV database.
      Data is available at https://www.themoviedb.org
    columns:
      - name: tmdb_id
        description: >-
          Unique identifier for each movie. This unique identifier comes from
          the tmdb API: https://developer.themoviedb.org/
        meta:
          dimension:
            type: number
      - name: title
        description: Title of the movie.
        meta:
          dimension:
            type: string
      - name: overview
        description: Brief description or summary of the movie.
        meta:
          dimension:
            type: string
      - name: tagline
        description: Catchphrase or memorable line associated with the movie.
        meta:
          dimension:
            type: string
      - name: spoken_languages
        description: List of languages spoken in the movie.
        meta:
          dimension:
            type: string
      - name: original_language
        description: Original language in which the movie was produced.
        meta:
          dimension:
            type: string
      - name: keywords
        description: Keywords associated with the movie.
        meta:
          dimension:
            type: string
      - name: status
        description: >-
          The status of the movie (e.g., Released, Rumored, Post Production,
          etc.).
        meta:
          dimension:
            type: string
      - name: video
        description: Indicates if the movie is suitable only for adult audiences.
        meta:
          dimension:
            type: boolean
      - name: vote_average
        description: Average vote or rating given by viewers.
        meta:
          dimension:
            type: number
      - name: budget
        description: Budget allocated for the movie in USD.
        meta:
          dimension:
            type: number
      - name: revenue
        description: Total revenue generated by the movie in USD.
        meta:
          dimension:
            type: number
      - name: runtime
        description: Duration of the movie in minutes.
        meta:
          dimension:
            type: number
      - name: release_date
        description: Date when the movie was released.
        meta:
          dimension:
            type: date
      - name: belongs_to_collection
        description: Collection to which the movie belongs, if applicable.
        meta:
          dimension:
            type: string
      - name: poster_path
        description: URL of the movie poster image.
        meta:
          dimension:
            type: string
      - name: backdrop_path
        description: URL of the backdrop image for the movie.
        meta:
          dimension:
            type: string
      - name: homepage
        description: Official homepage URL of the movie.
        meta:
          dimension:
            type: string
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: original_title
        description: Original title of the movie.
        meta:
          dimension:
            type: string
      - name: vote_count
        description: Total count of votes received for the movie.
        meta:
          dimension:
            type: number
      - name: genre_names
        description: List of genre names the movie belongs to.
        meta:
          dimension:
            type: string
      - name: production_company_names
        description: List of production company names involved in the movie.
        meta:
          dimension:
            type: string
      - name: production_country_names
        description: List of production country names associated with the movie.
        meta:
          dimension:
            type: string

  - name: stg_omdb_movies
    description: Crowdsourced movie information available at https://www.omdbapi.com/
    columns:
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: title
        description: Title of the movie.
        meta:
          dimension:
            type: string
      - name: director
        description: Director(s) of the movie.
        meta:
          dimension:
            type: string
      - name: writer
        description: Writer(s) of the movie.
        meta:
          dimension:
            type: string
      - name: actors
        description: Main actor(s) or cast of the movie.
        meta:
          dimension:
            type: string
      - name: genre
        description: Genre(s) of the movie.
        meta:
          dimension:
            type: string
      - name: language
        description: Language(s) spoken in the movie.
        meta:
          dimension:
            type: string
      - name: country
        description: Country or countries where the movie was produced.
        meta:
          dimension:
            type: string
      - name: type
        description: Type or category of the movie (e.g., movie, series, episode).
        meta:
          dimension:
            type: string
      - name: plot
        description: Summary or plot of the movie.
        meta:
          dimension:
            type: string
      - name: rated
        description: Rating assigned to the movie (e.g., PG-13, R, etc.).
        meta:
          dimension:
            type: string
      - name: ratings
        description: Various ratings received by the movie.
        meta:
          dimension:
            type: string
      - name: metascore
        description: Metascore rating of the movie.
        meta:
          dimension:
            type: number
      - name: imdb_rating
        description: IMDb rating of the movie.
        meta:
          dimension:
            type: number
      - name: imdb_votes
        description: Number of votes received on IMDb.
        meta:
          dimension:
            type: number
      - name: released_date
        description: Date when the movie was released.
        meta:
          dimension:
            type: date
      - name: release_year
        description: Year when the movie was released.
        meta:
          dimension:
            type: number
      - name: runtime
        description: Duration of the movie in minutes.
        meta:
          dimension:
            type: number
      - name: dvd
        description: DVD release date of the movie.
        meta:
          dimension:
            type: string
      - name: box_office
        description: Total box office revenue generated by the movie.
        meta:
          dimension:
            type: number
      - name: poster
        description: URL of the movie poster image.
        meta:
          dimension:
            type: string
      - name: production
        description: Production company or companies behind the movie.
        meta:
          dimension:
            type: string
      - name: website
        description: Official website of the movie.
        meta:
          dimension:
            type: string
      - name: awards
        description: Awards won or nominations received by the movie.
        meta:
          dimension:
            type: string
      - name: tmdb_id
        description: TMDB ID of the movie.
        meta:
          dimension:
            type: number
            
  - name: stg_tmdb_tv_series
    columns:
      - name: id
        description: Unique identifier for each TV show.
        meta:
          dimension:
            type: number
      - name: name
        description: Title of the TV show.
        meta:
          dimension:
            type: string
      - name: overview
        description: Brief description or summary of the TV show.
        meta:
          dimension:
            type: string
      - name: tagline
        description: Catchphrase or memorable line associated with the TV show.
        meta:
          dimension:
            type: string
      - name: genre_names
        description: Genres associated with the TV show.
        meta:
          dimension:
            type: string
      - name: created_by_names
        description: Names of individuals or entities credited for creating the TV show.
        meta:
          dimension:
            type: string
      - name: original_language
        description: Original language in which the TV show was produced.
        meta:
          dimension:
            type: string
      - name: status
        description: Current status of the TV show (e.g., returning series, ended, cancelled, etc.).
        meta:
          dimension:
            type: string
      - name: in_production
        description: Indicates if the TV show is currently in production.
        meta:
          dimension:
            type: boolean
      - name: first_air_date
        description: Date when the TV show was first aired.
        meta:
          dimension:
            type: date
      - name: last_air_date
        description: Date when the TV show was last aired.
        meta:
          dimension:
            type: date
      - name: number_of_seasons
        description: Number of seasons in the TV show.
        meta:
          dimension:
            type: number
      - name: number_of_episodes
        description: Number of episodes in the TV show.
        meta:
          dimension:
            type: number
      - name: vote_average
        description: Average vote or rating given by viewers.
        meta:
          dimension:
            type: number
      - name: vote_count
        description: Total number of votes received by the TV show.
        meta:
          dimension:
            type: number
      - name: popularity
        description: Popularity score of the TV show.
        meta:
          dimension:
            type: number
      - name: poster_path
        description: URL path of the poster image for the TV show.
        meta:
          dimension:
            type: string
      - name: production_company_names
        description: Names of production companies associated with the TV show.
        meta:
          dimension:
            type: string


  - name: stg_imdb_crew
    description: Directors and writers for each movie provided by IMDB and available at https://www.imdb.com/interfaces/
    columns:
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: director
        description: Director of the movie. Each movie can have more than one.
        meta:
          dimension:
            type: string
      - name: writer
        description: Writer of the movie. Each movie can have more than one.
        meta:
          dimension:
            type: string

  - name: stg_imdb_directors
    description: Directors for each movie provided by IMDB and available at https://www.imdb.com/interfaces/
    columns:
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: director
        description: Director of the movie. Each movie can have more than one.
        meta:
          dimension:
            type: string

  - name: stg_imdb_writers
    description: Writers for each movie provided by IMDB and available at https://www.imdb.com/interfaces/
    columns:
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: writer
        description: Writer of the movie. Each movie can have more than one.
        meta:
          dimension:
            type: string

  - name: stg_imdb_movies
    description: Basic info for each movie provided by IMDB and available at https://www.imdb.com/interfaces/
    columns:
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: titletype
        description: Type (short, movie, game, video, etc).
        meta:
          dimension:
            type: string
      - name: primarytitle
        description: Title of the movie.
        meta:
          dimension:
            type: string
      - name: originaltitle
        description: Original title of the movie.
        meta:
          dimension:
            type: string
      - name: startyear
        description: Release year (or start year for TV series).
        meta:
          dimension:
            type: number
      - name: runtimeminutes
        description: Runtime in minutes.
        meta:
          dimension:
            type: number
      - name: genres
        description: Genres assigned to the movie.
        meta:
          dimension:
            type: string

  - name: stg_consumer_price_index
    description: Consumer Price Index for All Urban Consumers to find out how inflation affected the value of a dollar over time. Available at https://data.bls.gov/timeseries/CUUR0000SA0?years_option=all_years
    columns:
      - name: cpi_year
        description: Year.
        meta:
          dimension:
            type: number
      - name: cpi_month
        description: Month.
        meta:
          dimension:
            type: number
      - name: cpi_value
        description: CPI value.
        meta:
          dimension:
            type: number