version: 2
models:
  - name: stg_tmdb_movies
    columns:
      - name: tmdb_id
        description: >-
          Unique identifier for each movie. This unique identifier comes from
          the tmdb API: https://developer.themoviedb.org/
        meta:
          dimension:
            type: number
      - name: title
        description: Title of the movie.
        meta:
          dimension:
            type: string
      - name: overview
        description: Brief description or summary of the movie.
        meta:
          dimension:
            type: string
      - name: tagline
        description: Catchphrase or memorable line associated with the movie.
        meta:
          dimension:
            type: string
      - name: spoken_languages
        description: List of languages spoken in the movie.
        meta:
          dimension:
            type: string
      - name: original_language
        description: Original language in which the movie was produced.
        meta:
          dimension:
            type: string
      - name: keywords
        description: Keywords associated with the movie.
        meta:
          dimension:
            type: string
      - name: status
        description: >-
          The status of the movie (e.g., Released, Rumored, Post Production,
          etc.).
        meta:
          dimension:
            type: string
      - name: video
        description: Indicates if the movie is suitable only for adult audiences.
        meta:
          dimension:
            type: boolean
      - name: vote_average
        description: Average vote or rating given by viewers.
        meta:
          dimension:
            type: number
      - name: budget
        description: Budget allocated for the movie.
        meta:
          dimension:
            type: number
      - name: revenue
        description: Total revenue generated by the movie.
        meta:
          dimension:
            type: number
      - name: runtime
        description: Duration of the movie in minutes.
        meta:
          dimension:
            type: number
      - name: release_date
        description: Date when the movie was released.
        meta:
          dimension:
            type: date
      - name: belongs_to_collection
        description: Collection to which the movie belongs, if applicable.
        meta:
          dimension:
            type: string
      - name: poster_path
        description: URL of the movie poster image.
        meta:
          dimension:
            type: string
      - name: backdrop_path
        description: URL of the backdrop image for the movie.
        meta:
          dimension:
            type: string
      - name: homepage
        description: Official homepage URL of the movie.
        meta:
          dimension:
            type: string
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: original_title
        description: Original title of the movie.
        meta:
          dimension:
            type: string
      - name: vote_count
        description: Total count of votes received for the movie.
        meta:
          dimension:
            type: number
      - name: genre_names
        description: List of genre names the movie belongs to.
        meta:
          dimension:
            type: string
      - name: production_company_names
        description: List of production company names involved in the movie.
        meta:
          dimension:
            type: string
      - name: production_country_names
        description: List of production country names associated with the movie.
        meta:
          dimension:
            type: string
  - name: stg_omdb_movies
    columns:
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string
      - name: title
        description: Title of the movie.
        meta:
          dimension:
            type: string
      - name: director
        description: Director(s) of the movie.
        meta:
          dimension:
            type: string
      - name: writer
        description: Writer(s) of the movie.
        meta:
          dimension:
            type: string
      - name: actors
        description: Main actor(s) or cast of the movie.
        meta:
          dimension:
            type: string
      - name: genre
        description: Genre(s) of the movie.
        meta:
          dimension:
            type: string
      - name: language
        description: Language(s) spoken in the movie.
        meta:
          dimension:
            type: string
      - name: country
        description: Country or countries where the movie was produced.
        meta:
          dimension:
            type: string
      - name: type
        description: Type or category of the movie (e.g., movie, series, episode).
        meta:
          dimension:
            type: string
      - name: plot
        description: Summary or plot of the movie.
        meta:
          dimension:
            type: string
      - name: rated
        description: Rating assigned to the movie (e.g., PG-13, R, etc.).
        meta:
          dimension:
            type: string
      - name: ratings
        description: Various ratings received by the movie.
        meta:
          dimension:
            type: string
      - name: metascore
        description: Metascore rating of the movie.
        meta:
          dimension:
            type: number
      - name: imdb_rating
        description: IMDb rating of the movie.
        meta:
          dimension:
            type: number
      - name: imdb_votes
        description: Number of votes received on IMDb.
        meta:
          dimension:
            type: number
      - name: released_date
        description: Date when the movie was released.
        meta:
          dimension:
            type: date
      - name: release_year
        description: Year when the movie was released.
        meta:
          dimension:
            type: number
      - name: runtime
        description: Duration of the movie in minutes.
        meta:
          dimension:
            type: number
      - name: dvd
        description: DVD release date of the movie.
        meta:
          dimension:
            type: string
      - name: box_office
        description: Total box office revenue generated by the movie.
        meta:
          dimension:
            type: number
      - name: poster
        description: URL of the movie poster image.
        meta:
          dimension:
            type: string
      - name: production
        description: Production company or companies behind the movie.
        meta:
          dimension:
            type: string
      - name: website
        description: Official website of the movie.
        meta:
          dimension:
            type: string
      - name: awards
        description: Awards won or nominations received by the movie.
        meta:
          dimension:
            type: string
      - name: tmdb_id
        description: TMDB ID of the movie.
        meta:
          dimension:
            type: number
  - name: stg_movie_awards
    description: "This staging model processes and filters movie awards data to ensure no null movie entries."
    columns:
      - name: year_film
        description: "The year the film was released."
        meta:
          dimension:
            type: number
      - name: year_ceremony
        description: "The year the award ceremony took place."
        meta:
          dimension:
            type: number
      - name: category
        description: "The category of the award."
        meta:
          dimension:
            type: string
      - name: nominee
        description: "The name of the nominee."
        meta:
          dimension:
            type: string
      - name: movie
        description: "The title of the movie."
        meta:
          dimension:
            type: string
      - name: winner
        description: "Indicates if the nominee won the award (TRUE/FALSE)."
        meta:
          dimension:
            type: string
      - name: award
        description: "The name of the award."
        meta:
          dimension:
            type: string
  - name: stg_cpi
    description: "This staging model processes and renames columns for CPI data."
    columns:
      - name: calendar_year
        description: "The calendar year."
        meta:
          dimension:
            type: number
      - name: jan
        description: "Consumer Price Index (CPI) value for January."
        meta:
          dimension:
            type: number
      - name: feb
        description: "Consumer Price Index (CPI) value for February."
        meta:
          dimension:
            type: number
      - name: mar
        description: "Consumer Price Index (CPI) value for March."
        meta:
          dimension:
            type: number
      - name: apr
        description: "Consumer Price Index (CPI) value for April."
        meta:
          dimension:
            type: number
      - name: may
        description: "Consumer Price Index (CPI) value for May."
        meta:
          dimension:
            type: number
      - name: jun
        description: "Consumer Price Index (CPI) value for June."
        meta:
          dimension:
            type: number
      - name: jul
        description: "Consumer Price Index (CPI) value for July."
        meta:
          dimension:
            type: number
      - name: aug
        description: "Consumer Price Index (CPI) value for August."
        meta:
          dimension:
            type: number
      - name: sep
        description: "Consumer Price Index (CPI) value for September."
        meta:
          dimension:
            type: number
      - name: oct
        description: "Consumer Price Index (CPI) value for October."
        meta:
          dimension:
            type: number
      - name: nov
        description: "Consumer Price Index (CPI) value for November."
        meta:
          dimension:
            type: number
      - name: dec
        description: "Consumer Price Index (CPI) value for December."
        meta:
          dimension:
            type: number
  - name: stg_bomojo_releases
    description: "This staging model processes and filters Box Office Mojo release data to ensure valid gross values."
    columns:
      - name: imdb_id
        description: "The IMDb ID of the movie."
        meta:
          dimension:
            type: string
      - name: release_group
        description: "The release group of the movie."
        meta:
          dimension:
            type: string
      - name: rollout
        description: "The rollout strategy for the movie release."
        meta:
          dimension:
            type: string
      - name: markets
        description: "The number of markets in which the movie was released."
        meta:
          dimension:
            type: number
      - name: domestic_gross
        description: "Domestic gross revenue of the movie."
        meta:
          dimension:
            type: number
      - name: international_gross
        description: "International gross revenue of the movie."
        meta:
          dimension:
            type: number
      - name: worldwide_gross
        description: "Worldwide gross revenue of the movie."
        meta:
          dimension:
            type: number
  - name: stg_bomojo_countries
    description: "This staging model processes Box Office Mojo country data."
    columns:
      - name: imdb_id
        description: "The IMDb ID of the movie."
        meta:
          dimension:
            type: string
      - name: area
        description: "Area where the movie was released."
        meta:
          dimension:
            type: string
      - name: region
        description: "Region where the movie was released."
        meta:
          dimension:
            type: string
      - name: releases
        description: "Number of releases for the movie in the region."
        meta:
          dimension:
            type: number
      - name: lifetime_gross
        description: "Lifetime gross revenue generated by the movie in the region."
        meta:
          dimension:
            type: number