/*
Staging model for OMDB_MOVIES source table.

```dbt
columns:
  - name: imdb_id
    description: IMDb ID of the movie.
    meta:
      dimension:
        type: string
  - name: title
    description: Title of the movie.
    meta:
      dimension:
        type: string
  - name: director
    description: Director(s) of the movie.
    meta:
      dimension:
        type: string
  - name: writer
    description: Writer(s) of the movie.
    meta:
      dimension:
        type: string
  - name: actors
    description: Main actor(s) or cast of the movie.
    meta:
      dimension:
        type: string
  - name: genre
    description: Genre(s) of the movie.
    meta:
      dimension:
        type: string
  - name: language
    description: Language(s) spoken in the movie.
    meta:
      dimension:
        type: string
  - name: country
    description: Country or countries where the movie was produced.
    meta:
      dimension:
        type: string
  - name: type
    description: Type or category of the movie (e.g., movie, series, episode).
    meta:
      dimension:
        type: string
  - name: plot
    description: Summary or plot of the movie.
    meta:
      dimension:
        type: string
  - name: rated
    description: Rating assigned to the movie (e.g., PG-13, R, etc.).
    meta:
      dimension:
        type: string
  - name: ratings
    description: Various ratings received by the movie.
    meta:
      dimension:
        type: string
  - name: metacritic_rating
    description: Metascore rating of the movie. Normalized to a 0-1 scale.
    meta:
      dimension:
        type: number
  - name: imdb_rating
    description: IMDb rating of the movie. Normalized to a 0-1 scale.
    meta:
      dimension:
        type: number
  - name: imdb_votes
    description: Number of votes received on IMDb.
    meta:
      dimension:
        type: number
  - name: released_date
    description: Date when the movie was released.
    meta:
      dimension:
        type: date
  - name: release_year
    description: Year when the movie was released.
    meta:
      dimension:
        type: number
  - name: runtime
    description: Duration of the movie in minutes.
    meta:
      dimension:
        type: number
  - name: dvd
    description: DVD release date of the movie.
    meta:
      dimension:
        type: string
  - name: box_office
    description: Total box office revenue generated by the movie.
    meta:
      dimension:
        type: number
  - name: poster_path
    description: URL of the movie poster image.
    meta:
      dimension:
        type: string
  - name: production
    description: Production company or companies behind the movie.
    meta:
      dimension:
        type: string
  - name: website
    description: Official website of the movie.
    meta:
      dimension:
        type: string
  - name: awards
    description: Awards won or nominations received by the movie.
    meta:
      dimension:
        type: string
  - name: tmdb_id
    description: TMDB ID of the movie.
    meta:
      dimension:
        type: number
```
*/

{% set colums_with_na_s = ["DIRECTOR", "WRITER", "ACTORS", "GENRE", "LANGUAGE", "COUNTRY", "TYPE", "PLOT", "RATED", "PRODUCTION", "AWARDS", "DVD"] %}

WITH SOURCE AS (
  SELECT
    IMDB_ID,
    TITLE,
    {% for column_name in colums_with_na_s %}
      NULLIF({{ column_name }}, 'N/A') AS {{ column_name }},
    {%- endfor -%}
    RATINGS,
    METASCORE / 100.0 AS METACRITIC_RATING,
    IMDB_RATING / 10.0 AS IMDB_RATING,
    IMDB_VOTES,
    {# RELEASED_DATE, #}
    RELEASE_YEAR,
    RUNTIME,
    BOX_OFFICE,
    NULLIF(POSTER, 'N/A') AS POSTER_PATH,
    {# WEBSITE, #} 
    TMDB_ID
  FROM
    {{ source('PARADIME_MOVIE_CHALLENGE', 'OMDB_MOVIES') }}
)

SELECT *
FROM
  SOURCE
