select RELEASE_YEAR,
ROUND(AVG(IMDB_RATING),1) AS AVG_RATING,
ROUND(AVG(BOX_OFFICE),1) AS AVG_BOX_OFFICE,
ROUND(AVG(RUNTIME),1) AS AVG_RUN_TIME,
count(*) as ct
FROM
{{ source('PARADIME_MOVIE_CHALLENGE_EXTRA', 'OMDB_INFLATION_ADJUSTED') }}
WHERE RELEASE_YEAR>1960
and box_office is not null
GROUP BY RELEASE_YEAR
ORDER BY RELEASE_YEAR ASC



