/*
Staging model for TMDB_MOVIES source table.

```dbt
columns:
  - name: tmdb_id
    description: >-
      Unique identifier for each movie. This unique identifier comes from
      the tmdb API: https://developer.themoviedb.org/
    meta:
      dimension:
        type: number
  - name: title
    description: Title of the movie.
    meta:
      dimension:
        type: string
  - name: overview
    description: Brief description or summary of the movie.
    meta:
      dimension:
        type: string
  - name: tagline
    description: Catchphrase or memorable line associated with the movie.
    meta:
      dimension:
        type: string
  - name: spoken_languages
    description: List of languages spoken in the movie.
    meta:
      dimension:
        type: string
  - name: original_language
    description: Original language in which the movie was produced.
    meta:
      dimension:
        type: string
  - name: keywords
    description: Keywords associated with the movie.
    meta:
      dimension:
        type: string
  - name: status
    description: >-
      The status of the movie (e.g., Released, Rumored, Post Production,
      etc.).
    meta:
      dimension:
        type: string
  - name: video
    description: Indicates if the movie is suitable only for adult audiences.
    meta:
      dimension:
        type: boolean
  - name: vote_average
    description: Average vote or rating given by viewers.
    meta:
      dimension:
        type: number
  - name: budget
    description: Budget allocated for the movie.
    meta:
      dimension:
        type: number
  - name: revenue
    description: Total revenue generated by the movie.
    meta:
      dimension:
        type: number
  - name: runtime
    description: Duration of the movie in minutes.
    meta:
      dimension:
        type: number
  - name: release_date
    description: Date when the movie was released.
    meta:
      dimension:
        type: date
  - name: belongs_to_collection
    description: Collection to which the movie belongs, if applicable.
    meta:
      dimension:
        type: string
  - name: poster_path
    description: URL of the movie poster image.
    meta:
      dimension:
        type: string
  - name: backdrop_path
    description: URL of the backdrop image for the movie.
    meta:
      dimension:
        type: string
  - name: homepage
    description: Official homepage URL of the movie.
    meta:
      dimension:
        type: string
  - name: imdb_id
    description: IMDb ID of the movie.
    meta:
      dimension:
        type: string
  - name: original_title
    description: Original title of the movie.
    meta:
      dimension:
        type: string
  - name: vote_count
    description: Total count of votes received for the movie.
    meta:
      dimension:
        type: number
  - name: genre_names
    description: List of genre names the movie belongs to. Science-fiction is replaced with the abbreviation as Sci-Fi for consistency.
    meta:
      dimension:
        type: string
  - name: production_company_names
    description: List of production company names involved in the movie.
    meta:
      dimension:
        type: string
  - name: production_country_names
    description: List of production country names associated with the movie.
    meta:
      dimension:
        type: string
```
*/

WITH SOURCE AS (
  SELECT
    TMDB_ID,
    TITLE,
    NULLIF(ORIGINAL_TITLE, '') AS ORIGINAL_TITLE,
    NULLIF(OVERVIEW, '') AS OVERVIEW,
    NULLIF(TAGLINE, '') AS TAGLINE,
    KEYWORDS,
    ORIGINAL_LANGUAGE,
    STATUS,
    VIDEO,
    YEAR(RELEASE_DATE) AS RELEASE_YEAR,
    NULLIF(RUNTIME, 0) AS RUNTIME,
    NULLIF(BUDGET, 0) AS BUDGET,
    NULLIF(REVENUE, 0) AS REVENUE,
    VOTE_AVERAGE,
    VOTE_COUNT,
    {# HOMEPAGE, #} --Not needed
    IFF(POSTER_PATH IS NULL, NULL, CONCAT('https://image.tmdb.org/t/p/w600_and_h900_bestv2/', POSTER_PATH)) AS POSTER_PATH,
    {# BACKDROP_PATH, #} --Not needed
    BELONGS_TO_COLLECTION,
    NULLIF(IMDB_ID, '') AS IMDB_ID,
    REPLACE(GENRE_NAMES, 'Science Fiction', 'Sci-Fi') AS GENRE,
    SPOKEN_LANGUAGES,
    PRODUCTION_COMPANY_NAMES,
    PRODUCTION_COUNTRY_NAMES
  FROM
    {{ source('PARADIME_MOVIE_CHALLENGE', 'TMDB_MOVIES') }}
)

SELECT *
FROM
  SOURCE
