WITH GENRE_UNNEST AS (
SELECT TITLE,
adj_box_office AS BOX_OFFICE,
RELEASE_YEAR,
TRIM(g.value::string) AS GENRE
FROM 
{{ source('PARADIME_MOVIE_CHALLENGE_FINAL', 'OMDB_INFLATION_ADJUSTED') }} a
,LATERAL FLATTEN(INPUT => SPLIT(a.GENRE, ',')) g
WHERE RELEASE_YEAR between 1990 AND 2023
AND box_office is not null
),

box_office_x_genre AS (
SELECT RELEASE_YEAR,
GENRE,
avg(BOX_OFFICE) AS AVG_BOX_OFFICE
FROM GENRE_UNNEST
GROUP BY RELEASE_YEAR,
GENRE
),


ranked_by_year AS (SELECT 
RELEASE_YEAR,
GENRE,
RANK() OVER (PARTITION BY RELEASE_YEAR ORDER BY AVG_BOX_OFFICE DESC) AS RNK
FROM box_office_x_genre
)

SELECT DISTINCT RELEASE_YEAR,
GENRE,
RNK
FROM ranked_by_year
WHERE RNK<=5
ORDER BY RELEASE_YEAR,RNK ASC
