select
RELEASE_YEAR,
avg(RUNTIME) AS AVG_RUNTIME,
COUNT(*) AS TOTAL_FILMS
FROM
{{ source('PARADIME_MOVIE_CHALLENGE_FINAL', 'OMDB_INFLATION_ADJUSTED') }} a
WHERE ADJ_BOX_OFFICE>0
GROUP BY RELEASE_YEAR
ORDER BY RELEASE_YEAR ASC, AVG_RUNTIME