WITH DATE_SPINE AS (
  {{ date_spine("YEAR", "'1920-01-01'::DATE", "CURRENT_DATE") }}
)

SELECT
  DATE_PART('YEAR', DATE_YEAR) AS DATE_YEAR,
  FLOOR(DATE_PART('YEAR', DATE_YEAR) / 10) * 10 AS DECADE
FROM DATE_SPINE
